// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";

function AddTask(Props) {
  var addTask = Props.addTask;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setDay = match$1[1];
  var day = match$1[0];
  var match$2 = React.useState(function () {
        return false;
      });
  var setReminder = match$2[1];
  var reminder = match$2[0];
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    if (text === "") {
      window.alert("Please add a task");
      return ;
    }
    var id = String(Js_math.random_int(0, 1000000)) + text;
    Curry._1(addTask, {
          id: id,
          text: text,
          day: day,
          reminder: reminder
        });
    Curry._1(setText, (function (param) {
            return "";
          }));
    Curry._1(setDay, (function (param) {
            return "";
          }));
    return Curry._1(setReminder, (function (param) {
                  return false;
                }));
  };
  return React.createElement("form", {
              className: "add-form",
              onSubmit: onSubmit
            }, React.createElement("div", {
                  className: "form-control"
                }, React.createElement("label", undefined, "Task"), React.createElement("input", {
                      name: "text",
                      placeholder: "Add Task",
                      type: "text",
                      value: text,
                      onChange: (function ($$event) {
                          var value = $$event.target.value;
                          return Curry._1(setText, (function (param) {
                                        return value;
                                      }));
                        })
                    })), React.createElement("div", {
                  className: "form-control"
                }, React.createElement("label", undefined, "Day & Time"), React.createElement("input", {
                      name: "day",
                      placeholder: "Add Day & Time",
                      type: "text",
                      value: day,
                      onChange: (function ($$event) {
                          var value = $$event.target.value;
                          return Curry._1(setDay, (function (param) {
                                        return value;
                                      }));
                        })
                    })), React.createElement("div", {
                  className: "form-control form-control-check"
                }, React.createElement("label", undefined, "Set Reminder"), React.createElement("input", {
                      name: "reminder",
                      type: "checkbox",
                      onChange: (function ($$event) {
                          var value = $$event.target.checked;
                          return Curry._1(setReminder, (function (param) {
                                        return value;
                                      }));
                        })
                    })), React.createElement("input", {
                  className: "btn btn-block",
                  type: "submit",
                  value: "Save Task"
                }));
}

var make = AddTask;

export {
  make ,
  
}
/* react Not a pure module */
