// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TaskTracker$MyResApp from "./TaskTracker.bs.js";

import './App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement(TaskTracker$MyResApp.make, {}));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
