// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Button(Props) {
  var children = Props.children;
  var color = Props.color;
  var onClick = Props.onClick;
  var style = {
    backgroundColor: color
  };
  var onClick$1 = function (param) {
    if (onClick !== undefined) {
      return Curry._1(onClick, undefined);
    }
    
  };
  return React.createElement("button", {
              className: "btn",
              style: style,
              onClick: onClick$1
            }, children);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
