// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$MyResApp from "./Button.bs.js";

function Header(Props) {
  var showAddTask = Props.showAddTask;
  var toogleShowAddTask = Props.toogleShowAddTask;
  var title = Props.title;
  var match = showAddTask ? [
      "red",
      "Close"
    ] : [
      "green",
      "Add Task"
    ];
  return React.createElement("div", {
              className: "header"
            }, React.createElement("h1", undefined, title), React.createElement(Button$MyResApp.make, {
                  children: match[1],
                  color: match[0],
                  onClick: toogleShowAddTask
                }));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
