// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Task$MyResApp from "./Task.bs.js";
import * as Header$MyResApp from "./Header.bs.js";
import * as AddTask$MyResApp from "./AddTask.bs.js";

function TaskTracker(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setShowAddTask = match[1];
  var showAddTask = match[0];
  var toogleShowAddTask = function (param) {
    return Curry._1(setShowAddTask, (function (prev) {
                  return !prev;
                }));
  };
  var match$1 = React.useState(function () {
        return Task$MyResApp.defaultTasks;
      });
  var setTodos = match$1[1];
  var addTask = function (task) {
    return Curry._1(setTodos, (function (prevTodos) {
                  return Belt_Array.concat(prevTodos, [task]);
                }));
  };
  var deleteTask = function (id) {
    return Curry._1(setTodos, (function (prevTodos) {
                  return prevTodos.filter(function (task) {
                              return task.id !== id;
                            });
                }));
  };
  var toggleReminder = function (id) {
    return Curry._1(setTodos, (function (prevTodos) {
                  return prevTodos.map(function (task) {
                              if (task.id === id) {
                                return {
                                        id: task.id,
                                        text: task.text,
                                        day: task.day,
                                        reminder: !task.reminder
                                      };
                              } else {
                                return task;
                              }
                            });
                }));
  };
  return React.createElement("div", undefined, React.createElement(Header$MyResApp.make, {
                  showAddTask: showAddTask,
                  toogleShowAddTask: toogleShowAddTask,
                  title: "Task Tracker"
                }), showAddTask ? React.createElement(AddTask$MyResApp.make, {
                    addTask: addTask
                  }) : null, React.createElement("div", undefined, match$1[0].map(function (task) {
                      return React.createElement(Task$MyResApp.make, {
                                  task: task,
                                  toggleReminder: toggleReminder,
                                  deleteTask: deleteTask,
                                  key: task.id
                                });
                    })));
}

var make = TaskTracker;

export {
  make ,
  
}
/* react Not a pure module */
