// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var defaultTasks = [
  {
    id: "a",
    text: "a",
    day: "a day",
    reminder: true
  },
  {
    id: "a",
    text: "a",
    day: "a day",
    reminder: true
  }
];

function Task(Props) {
  var task = Props.task;
  return React.createElement("div", {
              key: task.id
            }, React.createElement("div", {
                  className: "reminder"
                }, React.createElement("h3", undefined, task.text, React.createElement("i", {
                          className: "fas fa-times"
                        })), React.createElement("p", undefined, task.day)));
}

var make = Task;

export {
  defaultTasks ,
  make ,
  
}
/* react Not a pure module */
