// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Task$MyResApp from "./Task.bs.js";
import * as Button$MyResApp from "./Button.bs.js";

function TaskTracker(Props) {
  var match = React.useState(function () {
        return Task$MyResApp.defaultTasks;
      });
  var setTodos = match[1];
  var deleteTask = function (id) {
    return Curry._1(setTodos, (function (prevTodos) {
                  return prevTodos.filter(function (task) {
                              return task.id !== id;
                            });
                }));
  };
  var toggleReminder = function (id) {
    return Curry._1(setTodos, (function (prevTodos) {
                  return prevTodos.map(function (task) {
                              if (task.id === id) {
                                return {
                                        id: task.id,
                                        text: task.text,
                                        day: task.day,
                                        reminder: !task.reminder
                                      };
                              } else {
                                return task;
                              }
                            });
                }));
  };
  return React.createElement("div", {
              className: "todolist"
            }, React.createElement("header", {
                  className: "header"
                }, React.createElement("h1", undefined, "Task Tracker"), React.createElement(Button$MyResApp.make, {
                      children: "Add Task",
                      type: /* Add */0
                    })), React.createElement("ul", undefined, match[0].map(function (task) {
                      return React.createElement(Task$MyResApp.make, {
                                  task: task,
                                  toggleReminder: toggleReminder,
                                  deleteTask: deleteTask
                                });
                    })));
}

var make = TaskTracker;

export {
  make ,
  
}
/* react Not a pure module */
