// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var defaultTasks = [
  {
    id: "1",
    text: "Doctors Appointment",
    day: "September 1st at 2:30pm",
    reminder: true
  },
  {
    id: "2",
    text: "Meeting at Scholl",
    day: "September 3st at 1:30pm",
    reminder: false
  },
  {
    id: "3",
    text: "September 3st at 11:00am",
    day: "",
    reminder: true
  }
];

function Task(Props) {
  var task = Props.task;
  var toggleReminder = Props.toggleReminder;
  var deleteTask = Props.deleteTask;
  var className = task.reminder ? "task reminder" : "task";
  var onDoubleClick = function ($$event) {
    $$event.stopPropagation();
    return Curry._1(toggleReminder, task.id);
  };
  var onClick = function (param) {
    return Curry._1(deleteTask, task.id);
  };
  return React.createElement("div", {
              onDoubleClick: onDoubleClick
            }, React.createElement("div", {
                  className: className
                }, React.createElement("h3", undefined, task.text, React.createElement("span", {
                          className: "fas",
                          onClick: onClick
                        }, "x")), React.createElement("p", undefined, task.day)));
}

var make = Task;

export {
  defaultTasks ,
  make ,
  
}
/* react Not a pure module */
