// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Task$RescriptReactCrashCourseTodoList from "./Task.bs.js";
import * as Button$RescriptReactCrashCourseTodoList from "./Button.bs.js";

function TodoList(Props) {
  var match = React.useState(function () {
        return Task$RescriptReactCrashCourseTodoList.defaultTasks;
      });
  return React.createElement("div", {
              className: "todolist"
            }, React.createElement("header", {
                  className: "header"
                }, React.createElement("h1", undefined, "TodoList"), React.createElement(Button$RescriptReactCrashCourseTodoList.make, {
                      children: "Add Task",
                      type: /* Add */0
                    })), React.createElement("ul", undefined, match[0].map(function (task) {
                      return React.createElement(Task$RescriptReactCrashCourseTodoList.make, {
                                  task: task
                                });
                    })));
}

var make = TodoList;

export {
  make ,
  
}
/* react Not a pure module */
